$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json 
name: ML-Pipeline-Cluster
type: amlcompute
size: STANDARD_D2AS_V4
min_instances: 0
max_instances: 4
idle_time_before_scale_down: 1200